# Default values for go-filecoin-devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
Image: "657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin:fast-deploy-2"
StorageClassName: gp2
ProofParamsDir: "/opt/filecoin-proof-parameters"
Bootstrap:
  Replicas: 3
Miner:
  Replicas: 3
Sprinkler:
  CronJobConcurrencyPolicy: Forbid
  Schedule: "*/5 * * * *"
Genesis:
  WalletAddress: "t1m2lbhq3sgsv6524a5o76vtwitdjosqmounayv3i"
  MinerAddress: "t2xvao7yi3llzsvrdx7mbw4dtbw6wkav7lyzsbpoq"
