global:
  slack_api_url: $SLACK_API_URL

route:
  receiver: 'slack-alerts'
  group_by: ['alertname']
  group_wait: 500ms
  group_interval: 500ms
  repeat_interval: 5m

receivers:
  - name: 'slack-alerts'
    slack_configs:
    - channel: '#alerts'
      text: "{{ range .Alerts }}*Alert:* {{ .Annotations.description }}\n{{ end }}"
      send_resolved: true